[taxonomies]
skill = "skills"

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Skills'
pageRef = '/skills'
weight = 30

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
